version: '3.9'

services:
  corella:
    image: docker pull ghcr.io/yaviracjorge/landing:1.0.0
    networks:
      -traefik-public
    deploy:
      replicas: 1
      labels: 
        "traefik.enable=true"
        - "traefik.http.routers.corella.entrypoints=http"
        - "traefik.http.routers.corella.rule=Host(corella.byronrm.com)"
        - "traefik.http.middlewares.corella-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.corella.middlewares=corella-https-redirect"
        - "traefik.http.routers.corella-secure.entrypoints=https"
        - "traefik.http.routers.corella-secure.rule=Host(corella.byronrm.com)"
        - "traefik.http.routers.corella-secure.tls=true"
        - "traefik.http.routers.corella-secure.tls.certresolver=http"
        - "traefik.http.routers.corella-secure.service=corella"
        - "traefik.http.services.corella.loadbalancer.server.port=5000"
        - "traefik.docker.network=traefik-public"
  networks:
    traefik-public:
      external: true        